### ISSUE TITLE
Safari does not recognize the extension

### ISSUE THREAD

**Issue by Bokutowo** [PreMiD/Extension-Safari#2]
Hi, I just installed the PreMID extension but it looks like Safari doesn't detect it, so I can't activate it. 

https://user-images.githubusercontent.com/83189534/116011954-de649080-a627-11eb-9250-b150d7fe30af.mov

**Comment by rxri** [comment]
No, literally you were able to try these steps before creating an issue by just looking at internet because that's common issue when app is not signed with bought Apple Certificate.
 - Right click on .app then clicking `Open` and in another popup, click `Open` again.
 - You can always try close Safari and then try.
 -  Drag .app file into the Extensions window in Safari.

**Comment by Bokutowo** [comment]
I've already tried everything but it still doesn't seem to work.

**Comment by rxri** [comment]
If you don't have this full message:
![image](https://user-images.githubusercontent.com/9348108/116079030-a432d780-a697-11eb-95eb-8097dd87a522.png)
I think you can try do this:
 - System Preferences -> Security & Privacy -> General
 
![image](https://user-images.githubusercontent.com/9348108/116079176-c75d8700-a697-11eb-96cd-39bed9c53daf.png)
and set in `Allow apps downloaded from` to `App Store and identified developers`.

This thing is actually weird and sometimes fix itself after some reboots.

**Comment by BenjiThatFoxGuy** [comment]
I've all the settings as follows, and safari still doesn't see the extension.
the "wait for it to fix itself" solution is way to janky in my opinion.
I think you should just look into this, I've once fixed one issue but submitted the wrong version of a thing. happens.

**Comment by rxri** [comment]
Hey @ddomino007,
I'm really really sorry, but after testing on my new macOS Big Sur (11.2) installation, everything works perfectly and I can't test it since I don't have access to Catalina or High Sierra versions so if you want to help me solve this situation you can dm me on discord: ririxi#2721 and provide me more information like system version etc. It would really help me! Thank you!
*P.S. If @Bokutowo wants to help too, you can dm me too and provide same info.*

Regards,
**ririxi**.
Contact: mail@ririxi.dev, ririxi#2721.

**Comment by BenjiThatFoxGuy** [comment]
I would rather contribute than get assistance only for myself, because if the issue is present on two individual installations of totally different versions, then it suggests it may as well be unintentional bias that all is fine by the author OR just a very weird issue spanning more than one macOS version that we both were unlucky to experience (I use Big Sur as well, and the screenshot from @Bokutowo suggests they're running an earlier version). I've had this happen a lot with add ons outside the App Store with System Integrity disabled but this is no longer the case as my SIP is now enabled. I'm on Big Sur 11.2.3 (20D91), and the Safari version is 14.0.3 (16610.4.3.1.7). I've even tried enabling unsigned extensions just in case, and that didn't change much either.

**Comment by rxri** [comment]
Okay, thank you for information. I will try to upload there a build that is not signed by my Apple ID account and we will see if that will work for you. Please give me some time and when I will upload it, I will mention you so you will see it. Thank you ^w^

**Comment by Bokutowo** [comment]
If I can help you, I'm on macOS Big Sur (11.2.3) and the Safari version is 13.1.2 (15609.3.5.1.3). Like @ddomino007 I also tried enabling unsigned extensions, and that didn't make much difference either. And I’ve already allowed apps downloaded from App Store and identified developers. I hope this will be useful. :)

**Comment by ddomino007** [comment]
i don't know if it was something server side or what, but it started working by itself

**Comment by ririxidev** [comment]
Hi 👋 !!!
Sorry for not responding for a long long time! But I'm back with some news. For now I'm uploading PreMiD extension that is not signed - just for testing purposes. Could you check if this version works fine for you? Thanks!
[PreMiD-Extension.zip](https://github.com/PreMiD/Extension-Safari/files/6411754/PreMiD-Extension.zip)

**Comment by rxri** [comment]
Next update:
From what I noticed it's just faulty Swift Library that provides Safari data. I will try to fix it before next Extension update. Sorry for that but you can always try new BETA extension - because maybe it will fix it for you:
[PreMiD-Extension-2.2.4.1.app.zip](https://cdn.rcd.gg/PreMiD-Extension-v2.2.4.1-Safari.app.zip)
Edit found issue: Drop Extension file to `/Applications`. It should fix it because Gatekeeper is being weird. [Source](https://developer.apple.com/forums/thread/92591)

**Comment by rxri** [comment]
Should be fixed in 2.2.4 - if not I will re-open it.
